baseURL = "https://solidaireslucca.org/"
DefaultContentLanguage = "fr"
enableEmoji = true
enableRobotsTXT = true
languageCode = "fr-fr"
pygmentsCodefencesGuessSyntax = true
pygmentsCodeFences = true
pygmentsStyle = "trac"
pygmentsUseClasses = true
theme = "beautifulhugo"
title = "Solidaires Lucca"

[Author]
name = "Thomas Plaçais"

[params]
comments = false
commit = true
dateFormat = "02/01/2006"
delayDisqus = false
description = "Section syndicale Solidaires de Lucca"
disableMath = true
favicon = "img/logo_solidaires_carre.svg"
mainSections = ["posts"]
menu_item_separator = " · "
readingTime = false
rss = true
selfHosted = true
showRelatedPosts = false
SidebarRecentLimit = 5
socialShare = false
useHLJS = false
wordCount = false
hideAuthor = true

[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    disable = true
  [privacy.instagram]
    disable = true
  [privacy.twitter]
    disable = true
  [privacy.vimeo]
    disable = true
  [privacy.youtube]
    disable = true

[markup.goldmark.renderer]
unsafe= true

[[menu.main]]
name = "Le syndicat"
url = "posts/syndicat"
weight = 1

[[menu.main]]
name = "Nous contacter"
url = "page/contact"
weight = 1
